name: Build image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIETPI_IMG_NAME: DietPi_RPi-ARMv6-Bullseye
      OUTPUT_IMG_NAME: SailTrack-Ground_RPi-ARMv6-Bullseye
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SailTrack-Build
        run: sudo ./.build/sailtrack-build ${{ env.DIETPI_IMG_NAME }} ${{ env.OUTPUT_IMG_NAME }}

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_IMG_NAME }}.7z
          path: ${{ env.OUTPUT_IMG_NAME }}.7z
